module.exports = {
    GatewayVersion: 10,
    APIVersion: 10,
    Host: "https://discord.com",
    BaseURL: "/api/v10",

    GatewayOpcodes: {
        DISPATCH: 0,
        HEARTBEAT: 1,
        IDENTIFY: 2,
        PRESENCE_UPDATE: 3,
        VOICE_STATE_UPDATE: 4,
        RESUME: 6,
        RECONNECT: 7,
        REQUEST_GUILD_MEMBERS: 8,
        INVALID_SESSION: 9,
        HELLO: 10,
        HEARTBEAT_ACK: 11,
    },

    GatewayCloseCodes: {
        UNKNOWN_ERROR: 4000,
        UNKNOWN_OPCODE: 4001,
        DECODE_ERROR: 4002,
        NOT_AUTHENTICATED: 4003,
        AUTHENTICATION_FAILED: 4004,
        ALREADY_AUTHENTICATED: 4005,
        INVALID_SEQUENCE: 4007,
        RATE_LIMITED: 4008,
        SESSION_TIMEOUT: 4009,
        INVALID_SHARD: 4010,
        SHARDING_REQUIRED: 4011,
        INVALID_API_VERSION: 4012,
        INVALID_INTENTS: 4013,
        DISALLOWED_INTENTS: 4014,
    },

    Events: {
        READY: "ready",
        RECONNECTING: "reconnecting",
        DISCONNECTED: "disconnected",
        WARN: "warn",
        ERROR: "error",

        MESSAGE_CREATE: "messageCreate",
        INTERACTION_CREATE: "interactionCreate",
        GUILD_CREATE: "guildCreate",
        GUILD_DELETE: "guildDelete",
        GUILD_UPDATE: "guildUpdate",
        CHANNEL_CREATE: "channelCreate",
        CHANNEL_DELETE: "channelDelete",
        CHANNEL_UPDATE: "channelUpdate",

        WS_READY: "wsReady",
        WS_CLOSED: "wsClosed",
        WS_PACKET: "wsPacket",
        WS_ERROR: "wsError",
    },

    InteractionTypes: {
        PING: 1,
        APPLICATION_COMMAND: 2,
        MESSAGE_COMPONENT: 3,
        APPLICATION_COMMAND_AUTOCOMPLETE: 4,
        MODAL_SUBMIT: 5,
    },

    ComponentTypes: {
        ACTION_ROW: 1,
        BUTTON: 2,
        STRING_SELECT: 3,
        TEXT_INPUT: 4,
        USER_SELECT: 5,
        ROLE_SELECT: 6,
        MENTIONABLE_SELECT: 7,
        CHANNEL_SELECT: 8,
    },

    ButtonStyle: {
        PRIMARY: 1,
        SECONDARY: 2,
        SUCCESS: 3,
        DANGER: 4,
        LINK: 5,
    },

    ChannelTypes: {
        GUILD_TEXT: 0,
        DM: 1,
        GUILD_VOICE: 2,
        GROUP_DM: 3,
        GUILD_CATEGORY: 4,
        GUILD_ANNOUNCEMENT: 5,
        ANNOUNCEMENT_THREAD: 10,
        PUBLIC_THREAD: 11,
        PRIVATE_THREAD: 12,
        GUILD_STAGE_VOICE: 13,
        GUILD_DIRECTORY: 14,
        GUILD_FORUM: 15,
        GUILD_MEDIA: 16,
    },

    MessageFlags: {
        CROSSPOSTED: 1 << 0,
        IS_CROSSPOST: 1 << 1,
        SUPPRESS_EMBEDS: 1 << 2,
        SOURCE_MESSAGE_DELETED: 1 << 3,
        URGENT: 1 << 4,
        HAS_THREAD: 1 << 5,
        EPHEMERAL: 1 << 6,
        LOADING: 1 << 7,
        FAILED_TO_MENTION_SOME_ROLES_IN_THREAD: 1 << 8,
        SUPPRESS_NOTIFICATIONS: 1 << 12,
    },

    DefaultIntents: {
        GUILDS: 1 << 0,
        GUILD_MESSAGES: 1 << 9,
        GUILD_MESSAGE_REACTIONS: 1 << 10,
        DIRECT_MESSAGES: 1 << 12,
        DIRECT_MESSAGE_REACTIONS: 1 << 13,
        MESSAGE_CONTENT: 1 << 15,
    },

    ApplicationCommandTypes: {
        CHAT_INPUT: 1,
        USER: 2,
        MESSAGE: 3,
    },

    ApplicationCommandOptionTypes: {
        SUB_COMMAND: 1,
        SUB_COMMAND_GROUP: 2,
        STRING: 3,
        INTEGER: 4,
        BOOLEAN: 5,
        USER: 6,
        CHANNEL: 7,
        ROLE: 8,
        MENTIONABLE: 9,
        NUMBER: 10,
        ATTACHMENT: 11,
    },
    InteractionResponseTypes: {
        PONG: 1,
        CHANNEL_MESSAGE_WITH_SOURCE: 4,
        DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE: 5,
        DEFERRED_UPDATE_MESSAGE: 6,
        UPDATE_MESSAGE: 7,
        APPLICATION_COMMAND_AUTOCOMPLETE_RESULT: 8,
        MODAL: 9,
    },
};
